//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Holitech.rc
//
#define IDD_MAIN_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_BACKGROUND           129
#define IDR_TRAYMENU                    179
#define IDB_BITMAP_DOT_LARGE            181
#define IDB_BITMAP_0_LARGE              182
#define IDB_BITMAP_1_LARGE              183
#define IDB_BITMAP_2_LARGE              184
#define IDB_BITMAP_3_LARGE              185
#define IDB_BITMAP_4_LARGE              186
#define IDB_BITMAP_5_LARGE              187
#define IDB_BITMAP_6_LARGE              188
#define IDB_BITMAP_7_LARGE              189
#define IDB_BITMAP_8_LARGE              190
#define IDB_BITMAP_9_LARGE              191
#define IDB_BITMAP_MHZ                  192
#define IDB_BITMAP_Z_LARGE              212
#define IDB_BITMAP_B_LARGE              213
#define IDB_BITMAP_C_LARGE              214
#define IDB_BITMAP_D_LARGE              215
#define IDB_BITMAP_E_LARGE              216
#define IDB_BITMAP_F_LARGE              217
#define IDB_BITMAP_G_LARGE              218
#define IDB_BITMAP_H_LARGE              219
#define IDB_BITMAP_I_LARGE              220
#define IDB_BITMAP_J_LARGE              221
#define IDB_BITMAP_K_LARGE              222
#define IDB_BITMAP_L_LARGE              223
#define IDB_BITMAP_M_LARGE              224
#define IDB_BITMAP_N_LARGE              225
#define IDB_BITMAP_O_LARGE              226
#define IDB_BITMAP_P_LARGE              227
#define IDB_BITMAP_Q_LARGE              228
#define IDB_BITMAP_R_LARGE              229
#define IDB_BITMAP_S_LARGE              230
#define IDB_BITMAP_T_LARGE              231
#define IDB_BITMAP_U_LARGE              232
#define IDB_BITMAP_V_LARGE              233
#define IDB_BITMAP_W_LARGE              234
#define IDB_BITMAP_X_LARGE              235
#define IDB_BITMAP_Y_LARGE              236
#define IDB_BITMAP_A_LARGE              237
#define IDB_BITMAP_Z_SMALL              238
#define IDB_BITMAP_1_SMALL              239
#define IDB_BITMAP_2_SMALL              240
#define IDB_BITMAP_3_SMALL              241
#define IDB_BITMAP_4_SMALL              242
#define IDB_BITMAP_5_SMALL              243
#define IDB_BITMAP_6_SMALL              244
#define IDB_BITMAP_7_SMALL              245
#define IDB_BITMAP_8_SMALL              246
#define IDB_BITMAP_9_SMALL              247
#define IDB_BITMAP_A_SMALL              248
#define IDB_BITMAP_B_SMALL              249
#define IDB_BITMAP_C_SMALL              250
#define IDB_BITMAP_D_SMALL              251
#define IDB_BITMAP_E_SMALL              252
#define IDB_BITMAP_F_SMALL              253
#define IDB_BITMAP_G_SMALL              254
#define IDB_BITMAP_H_SMALL              255
#define IDB_BITMAP_Y_SMALL              256
#define IDB_BITMAP_I_SMALL              257
#define IDB_BITMAP_J_SMALL              258
#define IDB_BITMAP_K_SMALL              259
#define IDB_BITMAP_L_SMALL              260
#define IDB_BITMAP_M_SMALL              261
#define IDB_BITMAP_N_SMALL              262
#define IDB_BITMAP_O_SMALL              263
#define IDB_BITMAP_P_SMALL              264
#define IDB_BITMAP_Q_SMALL              265
#define IDB_BITMAP_R_SMALL              266
#define IDB_BITMAP_S_SMALL              267
#define IDB_BITMAP_T_SMALL              268
#define IDB_BITMAP_U_SMALL              269
#define IDB_BITMAP_V_SMALL              270
#define IDB_BITMAP_W_SMALL              271
#define IDB_BITMAP_X_SMALL              272
#define IDB_BITMAP_0_SMALL              273
#define IDB_BITMAP_DOT_SMALL            288
#define IDB_BITMAP_DASH_SMALL           289
#define IDB_BITMAP_APOSTROPHE_SMALL     290
#define IDB_BITMAP_SPACE_SMALL          291
#define IDB_BITMAP_SPACE_LARGE          292
#define IDB_BITMAP_EXCLAMATION_SMALL    293
#define IDB_BITMAP_AMPERSAND_SMALL      294
#define IDB_BITMAP_COMMA_SMALL          295
#define IDB_BITMAP_MODE                 300
#define IDB_BITMAP_P1                   301
#define IDB_BITMAP_P2                   302
#define IDB_BITMAP_P3                   303
#define IDB_BITMAP_P4                   304
#define IDB_BITMAP_P5                   305
#define IDB_BITMAP_P6                   306
#define IDB_BITMAP_MUTE                 307
#define IDB_BITMAP_NEXT                 308
#define IDB_BITMAP_PLAY                 309
#define IDB_BITMAP_PRE                  310
#define IDB_BITMAP_VOL_DN               311
#define IDB_BITMAP_VOL_UP               312
#define IDB_BITMAP_COOLSEAT             313
#define IDB_BITMAP_HEATSEAT             314
#define IDB_BITMAP_TEM_DN               315
#define IDB_BITMAP_TEM_UP               316
#define IDB_BITMAP_VEN_DN               317
#define IDB_BITMAP_VEN_UP               318
#define IDB_BITMAP_AC                   319
#define IDB_BITMAP_AIR                  320
#define IDB_BITMAP_AUTO                 321
#define IDB_BITMAP_FRONTHEAT            322
#define IDB_BITMAP_MAX_AC               323
#define IDB_BITMAP_REARHEAT             324
#define IDB_BITMAP_Z_SPECIAL            325
#define IDB_BITMAP_AC1                  337
#define IDB_BITMAP_AIR1                 338
#define IDB_BITMAP_AUTO1                339
#define IDB_BITMAP_BODYFOOT             340
#define IDB_BITMAP_BODYFOOT1            341
#define IDB_BITMAP_COOLSEAT1            342
#define IDB_BITMAP_COOLSEAT2            343
#define IDB_BITMAP_COOLSEAT3            344
#define IDB_BITMAP_FOOT                 345
#define IDB_BITMAP_FOOT1                346
#define IDB_BITMAP_FRONTHEAT1           347
#define IDB_BITMAP_HEAD                 348
#define IDB_BITMAP_HEAD1                349
#define IDB_BITMAP_HEADFOOT             350
#define IDB_BITMAP_HEADFOOT1            351
#define IDB_BITMAP_HEATSEAT1            352
#define IDB_BITMAP_HEATSEAT2            353
#define IDB_BITMAP_HEATSEAT3            354
#define IDB_BITMAP_MAX_AC1              355
#define IDB_BITMAP_REARHEAT1            356
#define IDB_BITMAP_COOLSEAT_CO          357
#define IDB_BITMAP_COOLSEAT1_CO         358
#define IDB_BITMAP_COOLSEAT2_CO         359
#define IDB_BITMAP_COOLSEAT3_CO         360
#define IDB_BITMAP_HEATSEAT_CO          361
#define IDB_BITMAP_HEATSEAT1_CO         362
#define IDB_BITMAP_HEATSEAT2_CO         363
#define IDB_BITMAP_HEATSEAT3_CO         364
#define IDB_BITMAP_TEM_DN_CO            365
#define IDB_BITMAP_TEM_UP_CO            366
#define IDB_BITMAP_VEN_ON1              367
#define IDB_BITMAP_VEN_ON2              368
#define IDB_BITMAP_VEN_ON3              369
#define IDB_BITMAP_VEN_ON4              370
#define IDB_BITMAP_VEN_ON5              371
#define IDB_BITMAP_VEN_ON6              372
#define IDB_BITMAP_VEN_ON7              373
#define IDB_BITMAP_VEN_OFF              374
#define IDB_BITMAP_MODE_1               375
#define IDB_BITMAP_MUTE_1               376
#define IDB_BITMAP_NEXT_1               377
#define IDB_BITMAP_P1_1                 378
#define IDB_BITMAP_P2_1                 379
#define IDB_BITMAP_P3_1                 380
#define IDB_BITMAP_P4_1                 381
#define IDB_BITMAP_P5_1                 382
#define IDB_BITMAP9                     383
#define IDB_BITMAP_P6_1                 383
#define IDB_BITMAP_PLAY_1               384
#define IDB_BITMAP_PRE_1                385
#define IDB_BITMAP_TEM_DN_1             386
#define IDB_BITMAP_TEM_DN_CO_1          387
#define IDB_BITMAP_TEM_UP_1             388
#define IDB_BITMAP_TEM_UP_CO_1          389
#define IDB_BITMAP_VEN_DN_1             390
#define IDB_BITMAP_VEN_UP_1             391
#define IDB_BITMAP_VOL_DN_1             392
#define IDB_BITMAP_VOL_UP_1             393
#define IDC_BUTTON_MODE                 1000
#define IDC_BUTTON_PRESET1              1001
#define IDC_BUTTON_PRESET2              1002
#define IDC_BUTTON_PRESET3              1003
#define IDC_BUTTON_PRESET4              1004
#define IDC_BUTTON_PRESET5              1005
#define IDC_BUTTON_PRESET6              1006
#define IDC_BUTTON_PRE                  1007
#define IDC_BUTTON_PLAY                 1008
#define IDC_BUTTON_NEXT                 1009
#define IDC_BUTTON_MUTE                 1010
#define IDC_BUTTON_VOL_DN               1011
#define IDC_BUTTON_VOL_UP               1012
#define IDC_BUTTON_MINIMIZE             1013
#define IDC_BUTTON_RESTORE              1014
#define IDC_BUTTON_CLOSE                1015
#define IDC_BUTTON_TEM_DN               1016
#define IDC_BUTTON_TEM_UP               1017
#define IDC_BUTTON_VEN_DN               1024
#define IDC_BUTTON_VEN_UP               1025
#define IDC_BUTTON_TEM_DN_CO            1026
#define IDC_BUTTON_TEM_UP_CO            1027
#define IDC_BUTTON_PRESETS              1042
#define IDC_BUTTON_HEATSEAT             1100
#define IDC_BUTTON_COOLSEAT             1104
#define IDC_BUTTON_HEATSEAT_CO          1108
#define IDC_BUTTON_COOLSEAT_CO          1112
#define IDC_BUTTON_BODYFOOT             1116
#define IDC_BUTTON_HEAD                 1118
#define IDC_BUTTON_FOOT                 1120
#define IDC_BUTTON_HEADFOOT             1122
#define IDC_BUTTON_FRONTHEAT            1124
#define IDC_BUTTON_REARHEAT             1126
#define IDC_BUTTON_AUTO                 1128
#define IDC_BUTTON_AC                   1130
#define IDC_BUTTON_MAX_AC               1132
#define IDC_BUTTON_AIR                  1134
#define ID_EXIT                         32771
#define ID_PRESET1                      32772
#define ID_PRESET2                      32773
#define ID_PRESET3                      32774
#define ID_PRESET4                      32775
#define ID_PRESET5                      32776
#define ID_PRESET6                      32777
#define ID_PRESET7                      32778
#define ID_PRESET8                      32779
#define ID_PRESET9                      32780
#define ID_PRESET10                     32781
#define ID_PRESET11                     32782
#define ID_PRESET12                     32783
#define ID_PREFERENCES                  32784
#define ID_SEEKUP                       32785
#define ID_SEEKDOWN                     32786
#define ID_SHOWRADIO                    32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        394
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
